/**
 * Generated by orval 🍺
 * Do not edit manually.
 * BookApp.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface BookResponse {
  id: string;
  title: string;
  author: string;
  publishedOn: string;
  createdAt: string;
}
