/**
 * Generated by orval 🍺
 * Do not edit manually.
 * BookApp.Api | v1
 * OpenAPI spec version: 1.0.0
 */

export interface QuoteResponse {
  id: string;
  text: string;
  /** @nullable */
  author: string | null;
  createdAt: string;
}
