/**
 * Generated by orval 🍺
 * Do not edit manually.
 * BookApp.Api | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpParams
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  Observable
} from 'rxjs';

import type {
  AuthResponse,
  BookRequest,
  BookResponse,
  LoginRequest,
  QuoteRequest,
  QuoteResponse,
  RegisterRequest
} from './model';

import {
  HttpHeaders
} from '@angular/common/http';
import type {
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';



interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?:
        | HttpParams
      | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: {includeHeaders?: string[]} | boolean;
  readonly timeout?: number;
}

type HttpClientBodyOptions = HttpClientOptions & {
  readonly observe?: 'body';
};

type HttpClientEventOptions = HttpClientOptions & {
  readonly observe: 'events';
};

type HttpClientResponseOptions = HttpClientOptions & {
  readonly observe: 'response';
};

type HttpClientObserveOptions = HttpClientOptions & {
  readonly observe?: 'body' | 'events' | 'response';
};





export type GetApiQuotesAccept = typeof GetApiQuotesAccept[keyof typeof GetApiQuotesAccept];

export const GetApiQuotesAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

export type PostApiQuotesAccept = typeof PostApiQuotesAccept[keyof typeof PostApiQuotesAccept];

export const PostApiQuotesAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

export type GetApiQuotesIdAccept = typeof GetApiQuotesIdAccept[keyof typeof GetApiQuotesIdAccept];

export const GetApiQuotesIdAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

export type PutApiQuotesIdAccept = typeof PutApiQuotesIdAccept[keyof typeof PutApiQuotesIdAccept];

export const PutApiQuotesIdAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

export type GetApiBooksAccept = typeof GetApiBooksAccept[keyof typeof GetApiBooksAccept];

export const GetApiBooksAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

export type PostApiBooksAccept = typeof PostApiBooksAccept[keyof typeof PostApiBooksAccept];

export const PostApiBooksAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

export type GetApiBooksIdAccept = typeof GetApiBooksIdAccept[keyof typeof GetApiBooksIdAccept];

export const GetApiBooksIdAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

export type PutApiBooksIdAccept = typeof PutApiBooksIdAccept[keyof typeof PutApiBooksIdAccept];

export const PutApiBooksIdAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

export type PostApiAuthRegisterAccept = typeof PostApiAuthRegisterAccept[keyof typeof PostApiAuthRegisterAccept];

export const PostApiAuthRegisterAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

export type PostApiAuthLoginAccept = typeof PostApiAuthLoginAccept[keyof typeof PostApiAuthLoginAccept];

export const PostApiAuthLoginAccept = {
  text_plain: 'text/plain',
  application_json: 'application/json',
  text_json: 'text/json',
} as const;

@Injectable({ providedIn: 'root' })
export class BookAppApiV1Service {
  private readonly http = inject(HttpClient);
 getApiQuotes(accept: 'text/plain', options?: HttpClientOptions): Observable<string>;
  getApiQuotes(accept: 'application/json', options?: HttpClientOptions): Observable<QuoteResponse[]>;
  getApiQuotes(accept: 'text/json', options?: HttpClientOptions): Observable<QuoteResponse[]>;
  getApiQuotes(accept?: GetApiQuotesAccept, options?: HttpClientOptions): Observable<QuoteResponse[] | string>;
  getApiQuotes(
    accept: GetApiQuotesAccept = 'application/json',
    options?: HttpClientOptions
  ): Observable<QuoteResponse[] | string> {
    const headers = options?.headers instanceof HttpHeaders
      ? options.headers.set('Accept', accept)
      : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http.get<QuoteResponse[]>(`/api/quotes`, {
        ...options,
        responseType: 'json',
        headers,


      });
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.get(`/api/quotes`, {
        ...options,
        responseType: 'text',
        headers,


      }) as Observable<string>;
    }

    return this.http.get<QuoteResponse[]>(`/api/quotes`, {
        ...options,
        responseType: 'json',
        headers,


      });
  }

 postApiQuotes(quoteRequest: QuoteRequest,
    accept: 'text/plain', options?: HttpClientOptions): Observable<string>;
  postApiQuotes(quoteRequest: QuoteRequest,
    accept: 'application/json', options?: HttpClientOptions): Observable<QuoteResponse>;
  postApiQuotes(quoteRequest: QuoteRequest,
    accept: 'text/json', options?: HttpClientOptions): Observable<QuoteResponse>;
  postApiQuotes(quoteRequest: QuoteRequest,
    accept?: PostApiQuotesAccept, options?: HttpClientOptions): Observable<QuoteResponse | string>;
  postApiQuotes(
    quoteRequest: QuoteRequest,
    accept: PostApiQuotesAccept = 'application/json',
    options?: HttpClientOptions
  ): Observable<QuoteResponse | string> {
    const headers = options?.headers instanceof HttpHeaders
      ? options.headers.set('Accept', accept)
      : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http.post<QuoteResponse>(`/api/quotes`, quoteRequest, {
        ...options,
        responseType: 'json',
        headers,


      });
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.post(`/api/quotes`, quoteRequest, {
        ...options,
        responseType: 'text',
        headers,


      }) as Observable<string>;
    }

    return this.http.post<QuoteResponse>(`/api/quotes`, quoteRequest, {
        ...options,
        responseType: 'json',
        headers,


      });
  }

 getApiQuotesId(id: string,
    accept: 'text/plain', options?: HttpClientOptions): Observable<string>;
  getApiQuotesId(id: string,
    accept: 'application/json', options?: HttpClientOptions): Observable<QuoteResponse>;
  getApiQuotesId(id: string,
    accept: 'text/json', options?: HttpClientOptions): Observable<QuoteResponse>;
  getApiQuotesId(id: string,
    accept?: GetApiQuotesIdAccept, options?: HttpClientOptions): Observable<QuoteResponse | string>;
  getApiQuotesId(
    id: string,
    accept: GetApiQuotesIdAccept = 'application/json',
    options?: HttpClientOptions
  ): Observable<QuoteResponse | string> {
    const headers = options?.headers instanceof HttpHeaders
      ? options.headers.set('Accept', accept)
      : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http.get<QuoteResponse>(`/api/quotes/${id}`, {
        ...options,
        responseType: 'json',
        headers,


      });
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.get(`/api/quotes/${id}`, {
        ...options,
        responseType: 'text',
        headers,


      }) as Observable<string>;
    }

    return this.http.get<QuoteResponse>(`/api/quotes/${id}`, {
        ...options,
        responseType: 'json',
        headers,


      });
  }

 putApiQuotesId(id: string,
    quoteRequest: QuoteRequest,
    accept: 'text/plain', options?: HttpClientOptions): Observable<string>;
  putApiQuotesId(id: string,
    quoteRequest: QuoteRequest,
    accept: 'application/json', options?: HttpClientOptions): Observable<QuoteResponse>;
  putApiQuotesId(id: string,
    quoteRequest: QuoteRequest,
    accept: 'text/json', options?: HttpClientOptions): Observable<QuoteResponse>;
  putApiQuotesId(id: string,
    quoteRequest: QuoteRequest,
    accept?: PutApiQuotesIdAccept, options?: HttpClientOptions): Observable<QuoteResponse | string>;
  putApiQuotesId(
    id: string,
    quoteRequest: QuoteRequest,
    accept: PutApiQuotesIdAccept = 'application/json',
    options?: HttpClientOptions
  ): Observable<QuoteResponse | string> {
    const headers = options?.headers instanceof HttpHeaders
      ? options.headers.set('Accept', accept)
      : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http.put<QuoteResponse>(`/api/quotes/${id}`, quoteRequest, {
        ...options,
        responseType: 'json',
        headers,


      });
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.put(`/api/quotes/${id}`, quoteRequest, {
        ...options,
        responseType: 'text',
        headers,


      }) as Observable<string>;
    }

    return this.http.put<QuoteResponse>(`/api/quotes/${id}`, quoteRequest, {
        ...options,
        responseType: 'json',
        headers,


      });
  }

 deleteApiQuotesId<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiQuotesId<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiQuotesId<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiQuotesId<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/quotes/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/quotes/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/quotes/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }

 getApiBooks(accept: 'text/plain', options?: HttpClientOptions): Observable<string>;
  getApiBooks(accept: 'application/json', options?: HttpClientOptions): Observable<BookResponse[]>;
  getApiBooks(accept: 'text/json', options?: HttpClientOptions): Observable<BookResponse[]>;
  getApiBooks(accept?: GetApiBooksAccept, options?: HttpClientOptions): Observable<BookResponse[] | string>;
  getApiBooks(
    accept: GetApiBooksAccept = 'application/json',
    options?: HttpClientOptions
  ): Observable<BookResponse[] | string> {
    const headers = options?.headers instanceof HttpHeaders
      ? options.headers.set('Accept', accept)
      : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http.get<BookResponse[]>(`/api/books`, {
        ...options,
        responseType: 'json',
        headers,


      });
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.get(`/api/books`, {
        ...options,
        responseType: 'text',
        headers,


      }) as Observable<string>;
    }

    return this.http.get<BookResponse[]>(`/api/books`, {
        ...options,
        responseType: 'json',
        headers,


      });
  }

 postApiBooks(bookRequest: BookRequest,
    accept: 'text/plain', options?: HttpClientOptions): Observable<string>;
  postApiBooks(bookRequest: BookRequest,
    accept: 'application/json', options?: HttpClientOptions): Observable<BookResponse>;
  postApiBooks(bookRequest: BookRequest,
    accept: 'text/json', options?: HttpClientOptions): Observable<BookResponse>;
  postApiBooks(bookRequest: BookRequest,
    accept?: PostApiBooksAccept, options?: HttpClientOptions): Observable<BookResponse | string>;
  postApiBooks(
    bookRequest: BookRequest,
    accept: PostApiBooksAccept = 'application/json',
    options?: HttpClientOptions
  ): Observable<BookResponse | string> {
    const headers = options?.headers instanceof HttpHeaders
      ? options.headers.set('Accept', accept)
      : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http.post<BookResponse>(`/api/books`, bookRequest, {
        ...options,
        responseType: 'json',
        headers,


      });
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.post(`/api/books`, bookRequest, {
        ...options,
        responseType: 'text',
        headers,


      }) as Observable<string>;
    }

    return this.http.post<BookResponse>(`/api/books`, bookRequest, {
        ...options,
        responseType: 'json',
        headers,


      });
  }

 getApiBooksId(id: string,
    accept: 'text/plain', options?: HttpClientOptions): Observable<string>;
  getApiBooksId(id: string,
    accept: 'application/json', options?: HttpClientOptions): Observable<BookResponse>;
  getApiBooksId(id: string,
    accept: 'text/json', options?: HttpClientOptions): Observable<BookResponse>;
  getApiBooksId(id: string,
    accept?: GetApiBooksIdAccept, options?: HttpClientOptions): Observable<BookResponse | string>;
  getApiBooksId(
    id: string,
    accept: GetApiBooksIdAccept = 'application/json',
    options?: HttpClientOptions
  ): Observable<BookResponse | string> {
    const headers = options?.headers instanceof HttpHeaders
      ? options.headers.set('Accept', accept)
      : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http.get<BookResponse>(`/api/books/${id}`, {
        ...options,
        responseType: 'json',
        headers,


      });
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.get(`/api/books/${id}`, {
        ...options,
        responseType: 'text',
        headers,


      }) as Observable<string>;
    }

    return this.http.get<BookResponse>(`/api/books/${id}`, {
        ...options,
        responseType: 'json',
        headers,


      });
  }

 putApiBooksId(id: string,
    bookRequest: BookRequest,
    accept: 'text/plain', options?: HttpClientOptions): Observable<string>;
  putApiBooksId(id: string,
    bookRequest: BookRequest,
    accept: 'application/json', options?: HttpClientOptions): Observable<BookResponse>;
  putApiBooksId(id: string,
    bookRequest: BookRequest,
    accept: 'text/json', options?: HttpClientOptions): Observable<BookResponse>;
  putApiBooksId(id: string,
    bookRequest: BookRequest,
    accept?: PutApiBooksIdAccept, options?: HttpClientOptions): Observable<BookResponse | string>;
  putApiBooksId(
    id: string,
    bookRequest: BookRequest,
    accept: PutApiBooksIdAccept = 'application/json',
    options?: HttpClientOptions
  ): Observable<BookResponse | string> {
    const headers = options?.headers instanceof HttpHeaders
      ? options.headers.set('Accept', accept)
      : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http.put<BookResponse>(`/api/books/${id}`, bookRequest, {
        ...options,
        responseType: 'json',
        headers,


      });
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.put(`/api/books/${id}`, bookRequest, {
        ...options,
        responseType: 'text',
        headers,


      }) as Observable<string>;
    }

    return this.http.put<BookResponse>(`/api/books/${id}`, bookRequest, {
        ...options,
        responseType: 'json',
        headers,


      });
  }

 deleteApiBooksId<TData = void>(id: string, options?: HttpClientBodyOptions): Observable<TData>;
 deleteApiBooksId<TData = void>(id: string, options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 deleteApiBooksId<TData = void>(id: string, options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  deleteApiBooksId<TData = void>(
    id: string, options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.delete<TData>(
      `/api/books/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.delete<TData>(
      `/api/books/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.delete<TData>(
      `/api/books/${id}`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }

 postApiAuthRegister(registerRequest: RegisterRequest,
    accept: 'text/plain', options?: HttpClientOptions): Observable<string>;
  postApiAuthRegister(registerRequest: RegisterRequest,
    accept: 'application/json', options?: HttpClientOptions): Observable<AuthResponse>;
  postApiAuthRegister(registerRequest: RegisterRequest,
    accept: 'text/json', options?: HttpClientOptions): Observable<AuthResponse>;
  postApiAuthRegister(registerRequest: RegisterRequest,
    accept?: PostApiAuthRegisterAccept, options?: HttpClientOptions): Observable<AuthResponse | string>;
  postApiAuthRegister(
    registerRequest: RegisterRequest,
    accept: PostApiAuthRegisterAccept = 'application/json',
    options?: HttpClientOptions
  ): Observable<AuthResponse | string> {
    const headers = options?.headers instanceof HttpHeaders
      ? options.headers.set('Accept', accept)
      : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http.post<AuthResponse>(`/api/auth/register`, registerRequest, {
        ...options,
        responseType: 'json',
        headers,


      });
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.post(`/api/auth/register`, registerRequest, {
        ...options,
        responseType: 'text',
        headers,


      }) as Observable<string>;
    }

    return this.http.post<AuthResponse>(`/api/auth/register`, registerRequest, {
        ...options,
        responseType: 'json',
        headers,


      });
  }

 postApiAuthLogin(loginRequest: LoginRequest,
    accept: 'text/plain', options?: HttpClientOptions): Observable<string>;
  postApiAuthLogin(loginRequest: LoginRequest,
    accept: 'application/json', options?: HttpClientOptions): Observable<AuthResponse>;
  postApiAuthLogin(loginRequest: LoginRequest,
    accept: 'text/json', options?: HttpClientOptions): Observable<AuthResponse>;
  postApiAuthLogin(loginRequest: LoginRequest,
    accept?: PostApiAuthLoginAccept, options?: HttpClientOptions): Observable<AuthResponse | string>;
  postApiAuthLogin(
    loginRequest: LoginRequest,
    accept: PostApiAuthLoginAccept = 'application/json',
    options?: HttpClientOptions
  ): Observable<AuthResponse | string> {
    const headers = options?.headers instanceof HttpHeaders
      ? options.headers.set('Accept', accept)
      : { ...(options?.headers ?? {}), Accept: accept };

    if (accept.includes('json') || accept.includes('+json')) {
      return this.http.post<AuthResponse>(`/api/auth/login`, loginRequest, {
        ...options,
        responseType: 'json',
        headers,


      });
    } else if (accept.startsWith('text/') || accept.includes('xml')) {
      return this.http.post(`/api/auth/login`, loginRequest, {
        ...options,
        responseType: 'text',
        headers,


      }) as Observable<string>;
    }

    return this.http.post<AuthResponse>(`/api/auth/login`, loginRequest, {
        ...options,
        responseType: 'json',
        headers,


      });
  }

 getApiAuthMe<TData = void>( options?: HttpClientBodyOptions): Observable<TData>;
 getApiAuthMe<TData = void>( options?: HttpClientEventOptions): Observable<HttpEvent<TData>>;
 getApiAuthMe<TData = void>( options?: HttpClientResponseOptions): Observable<AngularHttpResponse<TData>>;
  getApiAuthMe<TData = void>(
     options?: HttpClientObserveOptions): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(
      `/api/auth/me`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
      }
    );
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(
      `/api/auth/me`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
      }
    );
    }

    return this.http.get<TData>(
      `/api/auth/me`,{
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'body',
      }
    );
  }

};

